version: '3.4'

services:
  valheim:
    image: valheimdocker
    container_name: valheim
    volumes: 
      - './valheim:/home/steam/valheim'
    ports:
      - '2456:2456/udp'
      - '2457:2457/udp'
      - '2458:2458/udp'
    environment:
      - SERVER_NAME=Valheim\ Docker
      - SERVER_PORT=2456
      - SERVER_PASSWORD=secret
      - SERVER_WORLD=Dedicated
    build:
      context: .
      dockerfile: ./Dockerfile